export interface Project {
  title: string;
  description: string;
  image: string;
  technologies: string[];
  githubUrl?: string;
  liveUrl?: string;
  productionUrl?: string;
  progress: number;
  securityRestricted?: boolean;
}

export interface ProjectTabs {
  Frontend: Project[];
  Backend: Project[];
  Lab: Project[];
  Other: Project[];
}

export const projectTabs: ProjectTabs = {
  Frontend: [
    {
      title: "Portfolio Website",
      description: "Modern portfolio website with atomic design pattern, Lab terminal animations, and responsive layout for showcasing projects and skills.",
      image: "/projects/placeholder.svg",
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Anime.js", "React"],
      githubUrl: "https://github.com/phutran1210dev/kali-portfolio",
      progress: 100,
    },
    {
      title: "E-Learning Platform",
      description: "Interactive online learning platform with course management, video streaming, progress tracking, and student-teacher interaction features. Built with modern React architecture.",
      image: "/projects/placeholder.svg",
      technologies: ["React", "JavaScript", "Redux", "CSS3", "HTML5"],
      githubUrl: "",
      liveUrl: "https://e-learning-app-one.vercel.app/",
      progress: 100,
    },
    {
      title: "IS Speaking Platform",
      description: "Interactive English speaking practice platform with speech recognition, pronunciation analysis, and real-time feedback. Built with modern web technologies and deployed on Vercel.",
      image: "/projects/placeholder.svg",
      technologies: ["React", "Next.js", "Redux", "Bootstrap", "Webpack", "Vercel"],
      githubUrl: "",
      liveUrl: "https://is-speaking.vercel.app/",
      progress: 95,
    },
    {
      title: "ShareGram",
      description: "Social media sharing platform with advanced content management, user interaction features, and real-time communication. Fully deployed production application with scalable architecture.",
      image: "/projects/placeholder.svg",
      technologies: ["React", "Redux", "JavaScript", "SCSS", "Tiger Pay", "Lodash"],
      githubUrl: "",
      productionUrl: "https://share-gram.com/",
      progress: 100,
    },
    {
      title: "Advanced Data Visualization Platform",
      description: "Enterprise-grade data visualization platform with real-time analytics, interactive dashboards, and machine learning insights. Built with modern web technologies for scalable data processing.",
      image: "/projects/placeholder.svg",
      technologies: ["React", "TypeScript", "D3.js", "WebGL", "WebAssembly", "Three.js"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Distributed Blockchain Application",
      description: "Advanced decentralized application with smart contract integration, cryptocurrency payments, and distributed consensus mechanisms. Features Web3 integration and DeFi protocols.",
      image: "/projects/placeholder.svg",
      technologies: ["React", "Web3.js", "Solidity", "Ethereum", "MetaMask", "IPFS"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Real-time Collaborative IDE",
      description: "Cloud-based collaborative development environment with real-time code editing, integrated debugging, and team collaboration features. Advanced code analysis and AI-powered suggestions.",
      image: "/projects/placeholder.svg",
      technologies: ["React", "WebRTC", "Monaco Editor", "Docker", "Kubernetes", "AI/ML"],
      githubUrl: "",
      progress: 0,
    }
  ],
  Backend: [
    {
      title: "Task Management REST API",
      description: "Professional task management system with user authentication, project organization, team collaboration, and real-time notifications. Features JWT authentication, role-based permissions, and comprehensive API documentation.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "Express", "MongoDB", "JWT", "Socket.io", "Swagger"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "E-commerce Backend API",
      description: "Complete e-commerce backend with product catalog, shopping cart, order processing, payment integration (Stripe), inventory management, and admin dashboard APIs. Includes automated testing and CI/CD pipeline.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "NestJS", "PostgreSQL", "Stripe", "Redis", "Docker", "Jest"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Real-time Chat System",
      description: "Scalable chat application backend with WebSocket connections, message persistence, file sharing, group chats, and user presence tracking. Implements message encryption and rate limiting.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "Socket.io", "Redis", "MongoDB", "Multer", "Rate Limiting"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Blog CMS with GraphQL",
      description: "Modern content management system with GraphQL API, markdown support, image optimization, SEO features, and multi-author capabilities. Features advanced query optimization and caching strategies.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "GraphQL", "Apollo Server", "MongoDB", "Cloudinary", "Redis"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Social Media API Platform",
      description: "Social networking backend with user profiles, posts, comments, likes, follow system, and news feed algorithm. Implements advanced database indexing and query optimization for performance.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "Express", "PostgreSQL", "Redis", "AWS S3", "Bull Queue"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Microservices Event System",
      description: "Event-driven microservices architecture with service discovery, message queuing, distributed logging, and health monitoring. Demonstrates advanced backend patterns and scalability concepts.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "Docker", "RabbitMQ", "Consul", "ELK Stack", "Prometheus"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "File Storage & CDN Service",
      description: "Cloud file storage service with upload optimization, image processing, CDN integration, and access control. Features automatic backup, file versioning, and bandwidth optimization.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "AWS S3", "CloudFront", "Sharp", "Multer", "Compression"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Enterprise CQRS Banking System",
      description: "Advanced banking platform using CQRS/Event Sourcing with NestJS. Features distributed transactions, saga patterns, domain-driven design, and advanced security. Implements complex financial workflows with audit trails.",
      image: "/projects/placeholder.svg",
      technologies: ["NestJS", "TypeScript", "CQRS", "Event Sourcing", "DDD", "Kafka", "PostgreSQL", "Redis", "Saga Pattern"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Multi-tenant SaaS Platform",
      description: "Enterprise-grade SaaS architecture with advanced tenant isolation, dynamic schema generation, custom decorators, interceptors, and guards. Features automated billing, usage analytics, and white-label customization.",
      image: "/projects/placeholder.svg",
      technologies: ["NestJS", "TypeScript", "Multi-tenancy", "Custom Decorators", "Interceptors", "Guards", "Prisma", "Bull Queue", "Stripe"],
      githubUrl: "",
      progress: 0,
    }
  ],
  Lab: [
    {
      title: "CTF Platform",
      description: "Full-featured Capture The Flag platform with dynamic challenges, real-time scoring, team management, and automated challenge deployment.",
      image: "/projects/placeholder.svg",
      technologies: ["Kali Linux", "Python", "Docker", "MySQL", "Security Frameworks"],
      githubUrl: "https://github.com/phutran1210dev/ctf-platform",
      progress: 100,
    },
    {
      title: "Threat Intelligence Dashboard",
      description: "Real-time threat intelligence aggregation and visualization dashboard with IOC tracking, threat actor profiling, and automated alert generation.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Vue.js", "D3.js", "Elasticsearch", "OSINT", "Network Analysis"],
      githubUrl: "https://github.com/phutran1210dev/threat-intel",
      progress: 100,
    },
    {
      title: "Vulnerability Assessment Tool",
      description: "Automated vulnerability assessment with detailed reporting and security framework integration.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Security Scanners", "Reporting Tools", "Assessment Frameworks"],
      progress: 100,
      securityRestricted: true,
    },
    {
      title: "Network Discovery Tool",
      description: "Educational network reconnaissance tool for discovering network services and topology mapping. Focused on learning network protocols and security assessment fundamentals.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Network Protocols", "Threading", "CLI Tools"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Web Security Testing Framework",
      description: "Security testing framework for web application assessment and defense validation.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Web Security", "Testing Frameworks", "Encoding Methods"],
      githubUrl: "",
      progress: 0,
      securityRestricted: true,
    },
    {
      title: "Security Assessment Laboratory",
      description: "Controlled environment for security research and defense mechanism testing.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Security Frameworks", "Virtual Environments", "Assessment Tools"],
      progress: 0,
      securityRestricted: true,
    },
    {
      title: "Security Awareness Platform",
      description: "Educational platform for security awareness training and phishing simulation campaigns. Helps organizations test and improve their security posture through controlled assessments.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Web Frameworks", "Email Systems", "Training Modules"],
      progress: 0,
    },
    {
      title: "Wireless Security Assessment",
      description: "Wireless network security assessment toolkit for enterprise WiFi infrastructure evaluation.",
      image: "/projects/placeholder.svg",
      technologies: ["Kali Linux", "Wireless Tools", "Network Analysis", "Security Assessment"],
      progress: 0,
      securityRestricted: true,
    },
    {
      title: "Digital Forensics Investigation Suite",
      description: "Professional digital forensics toolkit for incident response with memory analysis, file recovery, and evidence preservation. Features automated reporting and chain of custody documentation.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Forensics Tools", "Analysis Frameworks", "Evidence Management"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Phishing Awareness Training Platform",
      description: "Educational tool to help users recognize phishing attempts through interactive simulations and awareness campaigns. Features real-time feedback and comprehensive reporting for organizational training programs.",
      image: "/projects/placeholder.svg",
      technologies: ["React", "Node.js", "MongoDB", "Email Templates", "Training Analytics"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Email Security Analysis Tool",
      description: "Advanced tool for analyzing suspicious emails and attachments to identify potential threats. Includes header analysis, attachment scanning, and malware detection capabilities for cybersecurity professionals.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Email Parser", "Threat Intelligence", "Sandbox Analysis", "Reporting"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Security Awareness Dashboard",
      description: "Comprehensive platform for training users about various security threats including social engineering, malware, and data protection. Features interactive modules and progress tracking for enterprise security training.",
      image: "/projects/placeholder.svg",
      technologies: ["Vue.js", "Express", "PostgreSQL", "D3.js", "Learning Management"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Anti-Phishing Browser Extension",
      description: "Protective browser extension that helps users identify and avoid phishing websites through real-time URL analysis and threat detection. Includes user alerts and safe browsing recommendations.",
      image: "/projects/placeholder.svg",
      technologies: ["JavaScript", "WebExtensions API", "Threat Detection", "URL Analysis", "Chrome/Firefox"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "NPM Package Security Scanner",
      description: "Advanced tool to detect malicious packages before installation through static analysis, behavior monitoring, and threat intelligence integration. Protects developers from supply chain attacks and compromised dependencies.",
      image: "/projects/placeholder.svg",
      technologies: ["Node.js", "Static Analysis", "Threat Intelligence", "Package Registry API", "Security Scanning"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Dependency Vulnerability Analyzer",
      description: "Comprehensive scanner that analyzes project dependencies for known security vulnerabilities, outdated packages, and licensing issues. Provides detailed remediation guidance and automated security reporting.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "CVE Database", "SBOM Generation", "Vulnerability Scanning", "Risk Assessment"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Supply Chain Security Toolkit",
      description: "Enterprise-grade toolkit that monitors and protects against supply chain attacks through dependency tracking, integrity verification, and continuous security monitoring of third-party components.",
      image: "/projects/placeholder.svg",
      technologies: ["Go", "Blockchain Verification", "CI/CD Integration", "Security Monitoring", "SLSA Framework"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Package Integrity Verification Tool",
      description: "Cryptographic verification tool that validates package authenticity and signatures through hash verification, digital signatures, and provenance tracking to ensure software supply chain integrity.",
      image: "/projects/placeholder.svg",
      technologies: ["Rust", "Cryptographic Hashing", "Digital Signatures", "Provenance Tracking", "SBOM Validation"],
      githubUrl: "",
      progress: 0,
    },
  ],
  Other: [
    {
      title: "Mobile Chat App",
      description: "Cross-platform mobile application for real-time messaging with end-to-end encryption and multimedia sharing capabilities.",
      image: "/projects/placeholder.svg",
      technologies: ["React Native", "Firebase", "TypeScript", "Redux", "Expo"],
      githubUrl: "https://github.com/phutran1210dev/chat-app",
      liveUrl: "https://chat-app-demo.com",
      productionUrl: "https://chat.phutran.dev",
      progress: 88,
    },
    {
      title: "AI Content Generator",
      description: "AI-powered content generation tool with natural language processing, multiple output formats, and customizable templates.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "OpenAI API", "Streamlit", "NLP", "Machine Learning"],
      githubUrl: "https://github.com/phutran1210dev/ai-generator",
      liveUrl: "https://ai-generator.com",
      productionUrl: "https://ai.phutran.dev",
      progress: 92,
    },
    {
      title: "Basic Image Classifier",
      description: "Beginner-friendly image classification model using pre-trained networks to categorize everyday objects. Perfect introduction to computer vision and deep learning fundamentals.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "TensorFlow", "Keras", "CNN", "Image Processing"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Sentiment Analysis Bot",
      description: "Simple natural language processing bot that analyzes text sentiment from social media posts and reviews. Implements basic NLP techniques and text preprocessing.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "NLTK", "Scikit-learn", "Pandas", "Text Processing"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Recommendation System",
      description: "Collaborative filtering recommendation engine for movies and products. Demonstrates machine learning concepts including user-item interactions and similarity algorithms.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Pandas", "NumPy", "Collaborative Filtering", "Matrix Factorization"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Chatbot with NLP",
      description: "Intermediate conversational AI chatbot with natural language understanding and context awareness. Features intent recognition and response generation capabilities.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "spaCy", "RASA", "Intent Recognition", "Dialogue Management"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Computer Vision Object Detection",
      description: "Advanced real-time object detection system using YOLO and OpenCV. Capable of detecting and tracking multiple objects in video streams with bounding box annotations.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "YOLO", "OpenCV", "PyTorch", "Real-time Processing"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Generative AI Art Platform",
      description: "Creative AI platform that generates artwork using Generative Adversarial Networks (GANs) and Diffusion Models. Features style transfer and custom art generation capabilities.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "PyTorch", "GANs", "Diffusion Models", "Style Transfer"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Language Translation API",
      description: "Multi-language translation service using transformer architectures and attention mechanisms. Supports real-time translation with high accuracy across multiple language pairs.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Transformers", "Hugging Face", "BERT", "Attention Mechanisms"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Advanced Deep Learning Framework",
      description: "Custom deep learning framework with automatic differentiation, GPU acceleration, and distributed training capabilities. Implements state-of-the-art optimization algorithms and neural network architectures.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "CUDA", "Distributed Computing", "Automatic Differentiation", "Neural Architecture Search"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "AI-Powered Code Assistant",
      description: "Intelligent code completion and generation tool powered by large language models. Features code understanding, bug detection, and automated refactoring suggestions.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Large Language Models", "Code Analysis", "AST Parsing", "AI Code Generation"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Reinforcement Learning Game AI",
      description: "Advanced AI agent trained using reinforcement learning to master complex strategy games. Implements Deep Q-Networks, Policy Gradients, and Multi-Agent systems.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "Reinforcement Learning", "Deep Q-Networks", "Policy Gradients", "Multi-Agent Systems"],
      githubUrl: "",
      progress: 0,
    },
    {
      title: "Personal AI Face Recognition System",
      description: "Advanced personal face detection and recognition system with real-time processing capabilities. Features facial landmark detection, emotion recognition, and secure biometric authentication for personal use.",
      image: "/projects/placeholder.svg",
      technologies: ["Python", "OpenCV", "dlib", "Face Recognition", "Deep Learning", "Real-time Processing"],
      githubUrl: "",
      progress: 0,
    }
  ]
};

export type ProjectTabKey = keyof ProjectTabs;